kobo/hub/forms.py
# -*- coding: utf-8 -*-


import django.forms as forms
from django.db.models import Q
from kobo.django.helpers import call_if_callable
from kobo.hub.models import Task


class TaskSearchForm(forms.Form):
    search  = forms.CharField(required=False)
    my  = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        self.state = kwargs.pop('state', None)
        self.order_by = kwargs.pop('order_by', ['-id'])
        return super(TaskSearchForm, self).__init__(*args, **kwargs)

    def get_query(self, request):
        self.is_valid()
        search = self.cleaned_data["search"]
        my = self.cleaned_data["my"]

        query = Q()

        if search:
            query |= Q(method__icontains=search)
            query |= Q(owner__username__icontains=search)
            query |= Q(label__icontains=search)

        if my and call_if_callable(request.user.is_authenticated):
            query &= Q(owner=request.user)

        if self.state is not None:
            query &= Q(state__in=self.state)
        #if self.kwargs:
        #    query &= Q(self.kwargs)
        return Task.objects.filter(parent__isnull=True).filter(query).order_by(*self.order_by).defer("result", "args").select_related("owner", "worker")

kobo/hub/templates/task/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans 'Task' %} #{{ task.id }}: {{ task.method }}</h2>

<h3>{% trans 'Details' %}</h3>
<table class="details">
  <tr>
    <th>{% trans "ID" %}</th>
    <td>{{ task.id }}</td>
  </tr>
  <tr>
    <th>{% trans "Method" %}</th>
    <td>{{ task.method }}</td>
  </tr>
  <tr>
    <th>{% trans "Args" %}</th>
    <td>{% for arg in task.get_args_display.items %}<b>{{ arg.0 }}:</b> {{ arg.1 }}<br />{% endfor %}</td>
  </tr>
  <tr>
    <th>{% trans "Label" %}</th>
    <td>{{ task.label }}</td>
  </tr>
  <tr>
    <th>{% trans "State" %}</th>
    <td class="{{ task.get_state_display }}">{{ task.get_state_display }}</td>
  </tr>

  {% if task.state == "CANCELED" %}
  <tr>
    <th>{% trans "Cancelled by" %}</th>
    {% if task.canceled_by %}
      <td>{{ task.canceled_by }}</td>
    {% else %}
      <td>Unavailable</td>
    {% endif %}
  </tr>
{% endif %}

  <tr>
    <th>{% trans "Worker" %}</th>
    <td>{% if task.worker %}{{ task.worker }}{% endif %}</td>
  </tr>
  <tr>
    <th>{% trans "Channel" %}</th>
    <td>{{ task.channel }}</td>
  </tr>
  <tr>
    <th>{% trans "Arch" %}</th>
    <td>{{ task.arch }}</td>
  </tr>

  <tr>
    <th>{% trans "Exclusive" %}</th>
    <td>{{ task.exclusive }}</td>
  </tr>
  <tr>
    <th>{% trans "Priority" %}</th>
    <td>{{ task.priority }}</td>
  </tr>
  <tr>
    <th>{% trans "Waiting" %}</th>
    <td>{{ task.waiting }}</td>
  </tr>
  <tr>
    <th>{% trans "Awaited" %}</th>
    <td>{{ task.awaited }}</td>
  </tr>
  <tr>
    <th>{% trans "Owner" %}</th>
    <td>{{ task.owner }}</td>
  </tr>
{% if task.resubmitted_by %}
  <tr>
    <th>{% trans "Resubmitted by" %}</th>
    <td>{{ task.resubmitted_by }}</td>
  </tr>
{% endif %}
{% if task.resubmitted_from %}
  <tr>
    <th>{% trans "Resubmitted from" %}</th>
    <td>#{{ task.resubmitted_from.id }} <a href="{% url 'task/detail' task.resubmitted_from.id %}">task</a></td>
  </tr>
{% endif %}
  <tr>
    <th>{% trans "Created" %}</th>
    <td>{% if task.dt_created %}{{ task.dt_created|date:"Y-m-d H:i:s" }}{% endif %}</td>
  </tr>
  <tr>
    <th>{% trans "Started" %}</th>
    <td>{% if task.dt_started %}{{ task.dt_started|date:"Y-m-d H:i:s" }}{% endif %}</td>
  </tr>
  <tr>
    <th>{% trans "Finished" %}</th>
    <td>{% if task.dt_finished %}{{ task.dt_finished|date:"Y-m-d H:i:s" }}{% endif %}</td>
  </tr>
  <tr>
      <th>{% trans "Spent time" %}</th>
      <td>{{ task.get_time_display }}</td>
  </tr>
  <tr>
    <th>{% trans "Comment" %}</th>
    <td>{% if task.comment %}{{ task.comment }}{% endif %}</td>
  </tr>
</table>


<h3>{% trans 'Result' %}</h3>
<pre class="log">
{{ task.result }}
</pre>


{% if logs %}
<h3>{% trans 'Logs' %}</h3>
<ul>
{% for log in logs %}
  <li><a href="{% url 'task/log' task.id log %}">{{ log }}</a> [<a href="{% url 'task/log' task.id log %}?format=raw">download</a>]</li>
{% endfor %}
</ul>
{% endif %}


{% if task_list %}
<h3>{% trans 'Subtask list' %}</h3>
{% include "task/list_include.html" %}
{% endif %}

{% endblock %}

kobo/hub/templates/task/list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Tasks" %}</h2>

<form method="GET" target="" style="float: left;">
    {{ form.search }}
    <input type="submit" value="{% trans "Search" %}" />
    {% if user.is_authenticated %}<br />{{ form.my }} <label for="id_my">{% trans "Show only my tasks" %}</label>{% endif %}
</form>

<br />
{% include "pagination.html" %}
{% include "task/list_include.html" %}
{% include "pagination.html" %}

{% endblock %}

kobo/hub/templates/task/list_include.html
{% load i18n %}

<table class="list" width="100%">
  <tr>
    <th>{% trans "ID" %}</th>
    <th>{% trans "Method" %}</th>
    <th>{% trans "Owner" %}</th>
    <th>{% trans "State" %}</th>
    <th>{% trans "Label" %}</th>
    <th>{% trans "Worker" %}</th>
    <th>{% trans "Created" %}</th>
    <th>{% trans "Finished" %}</th>
    <th>{% trans "Subtask #" %}</th>
  </tr>
{% for task in task_list %}
  <tr>
    <td><a href="{% url 'task/detail' task.id %}">{{ task.id }}</a></td>
    <td>{{ task.method }}</td>
    <td>{{ task.owner }}</td>
    <td class="{{ task.get_state_display }}">{{ task.get_state_display }}</td>
    <td>{{ task.label }}</td>
    <td>{% if task.worker %}{{ task.worker }}{% endif %}</td>
    <td>{{ task.dt_created|date:"Y-m-d H:i:s" }}</td>
    <td>{{ task.dt_finished|date:"Y-m-d H:i:s" }}</td>
    <td>{{ task.subtask_count }}</td>
  </tr>
{% endfor %}
</table>

kobo/hub/templates/task/log.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block head %}
<script type="text/javascript" src="{% static "kobo/js/log_watcher.js" %}"></script>
<script type="text/javascript" language="javascript">
document.log_watcher = new LogWatcher('{{ json_url }}', {{ offset }}, {{ task_finished }}, {{ next_poll }});
document.log_watcher.watch();
</script>
{% endblock %}

{% block content %}
<h2>{% trans 'Task' %} #{{ task.id }} - {{ log_name }}</h2>
<a href="{% url 'task/detail' task.id %}">{% trans "back to task" %} #{{ task.id }}</a><br />
<a href="?format=raw">{% trans 'download' %}</a>
<pre class="log" id="log">{{ content }}</pre>
{% endblock %}